language: rust
cache: cargo

matrix:
  include:
    - rust: stable
      os: linux
    - rust: nightly
      os: linux
    - rust: stable
      os: osx
    - rust: nightly
      os: osx

script:
    - cargo test
    - cargo test --features early-data
    - cd examples/server
    - cargo check
    - cd ../../examples/client
    - cargo check
